# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: afe449e1be34011e27c14932369158665a339c5145a52346de9869d8c1534d57a5d32c5d0e479ff2cc63e3983b0475dc40e9ab63bc128d8148a9397c120e0493

test:
  secret_key_base: 87513f7f2c14cf53ddee6d49ec1d38374c21ffe240716181b3b52a62d80b9d12df25207d350483226c4c634a3e980d4767fbeac9631c8c004cf9c1e217dff033

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
